// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB1XO61F4aC0i2RUsmPetTzsqjlRB_nxE',
    appId: '1:425320329389:web:1c91c0ca2d3ea78c605624',
    messagingSenderId: '425320329389',
    projectId: 'final-project-53d73',
    authDomain: 'final-project-53d73.firebaseapp.com',
    databaseURL: 'https://final-project-53d73-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-53d73.appspot.com',
    measurementId: 'G-GVJPP6RHQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT9G2l_rZ7kTceQYMTvXA_cfxjNQuKM9I',
    appId: '1:425320329389:android:de99ae5f6ffb204e605624',
    messagingSenderId: '425320329389',
    projectId: 'final-project-53d73',
    databaseURL: 'https://final-project-53d73-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-53d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSQVul-CC0o2QkTG9i2L1zulQafaL8Koc',
    appId: '1:425320329389:ios:1a3c8c5df7e9c9ba605624',
    messagingSenderId: '425320329389',
    projectId: 'final-project-53d73',
    databaseURL: 'https://final-project-53d73-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-53d73.appspot.com',
    iosClientId: '425320329389-ueebo3jemshk8vcoh15b9u1tplui8grs.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
